# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dineshn/iros_2015_1/constrained_BA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dineshn/iros_2015_1/constrained_BA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dineshn/iros_2015_1/constrained_BA/CMakeFiles /home/dineshn/iros_2015_1/constrained_BA/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dineshn/iros_2015_1/constrained_BA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ba2D3D

# Build rule for target.
ba2D3D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ba2D3D
.PHONY : ba2D3D

# fast build rule for target.
ba2D3D/fast:
	$(MAKE) -f CMakeFiles/ba2D3D.dir/build.make CMakeFiles/ba2D3D.dir/build
.PHONY : ba2D3D/fast

#=============================================================================
# Target rules for targets named ba2D3Dbox

# Build rule for target.
ba2D3Dbox: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ba2D3Dbox
.PHONY : ba2D3Dbox

# fast build rule for target.
ba2D3Dbox/fast:
	$(MAKE) -f CMakeFiles/ba2D3Dbox.dir/build.make CMakeFiles/ba2D3Dbox.dir/build
.PHONY : ba2D3Dbox/fast

#=============================================================================
# Target rules for targets named ba2D3DboxType1

# Build rule for target.
ba2D3DboxType1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ba2D3DboxType1
.PHONY : ba2D3DboxType1

# fast build rule for target.
ba2D3DboxType1/fast:
	$(MAKE) -f CMakeFiles/ba2D3DboxType1.dir/build.make CMakeFiles/ba2D3DboxType1.dir/build
.PHONY : ba2D3DboxType1/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

ba2D3D.o: ba2D3D.cc.o
.PHONY : ba2D3D.o

# target to build an object file
ba2D3D.cc.o:
	$(MAKE) -f CMakeFiles/ba2D3D.dir/build.make CMakeFiles/ba2D3D.dir/ba2D3D.cc.o
.PHONY : ba2D3D.cc.o

ba2D3D.i: ba2D3D.cc.i
.PHONY : ba2D3D.i

# target to preprocess a source file
ba2D3D.cc.i:
	$(MAKE) -f CMakeFiles/ba2D3D.dir/build.make CMakeFiles/ba2D3D.dir/ba2D3D.cc.i
.PHONY : ba2D3D.cc.i

ba2D3D.s: ba2D3D.cc.s
.PHONY : ba2D3D.s

# target to generate assembly for a file
ba2D3D.cc.s:
	$(MAKE) -f CMakeFiles/ba2D3D.dir/build.make CMakeFiles/ba2D3D.dir/ba2D3D.cc.s
.PHONY : ba2D3D.cc.s

ba2D3Dbox.o: ba2D3Dbox.cc.o
.PHONY : ba2D3Dbox.o

# target to build an object file
ba2D3Dbox.cc.o:
	$(MAKE) -f CMakeFiles/ba2D3Dbox.dir/build.make CMakeFiles/ba2D3Dbox.dir/ba2D3Dbox.cc.o
.PHONY : ba2D3Dbox.cc.o

ba2D3Dbox.i: ba2D3Dbox.cc.i
.PHONY : ba2D3Dbox.i

# target to preprocess a source file
ba2D3Dbox.cc.i:
	$(MAKE) -f CMakeFiles/ba2D3Dbox.dir/build.make CMakeFiles/ba2D3Dbox.dir/ba2D3Dbox.cc.i
.PHONY : ba2D3Dbox.cc.i

ba2D3Dbox.s: ba2D3Dbox.cc.s
.PHONY : ba2D3Dbox.s

# target to generate assembly for a file
ba2D3Dbox.cc.s:
	$(MAKE) -f CMakeFiles/ba2D3Dbox.dir/build.make CMakeFiles/ba2D3Dbox.dir/ba2D3Dbox.cc.s
.PHONY : ba2D3Dbox.cc.s

ba2D3DboxType.o: ba2D3DboxType.cc.o
.PHONY : ba2D3DboxType.o

# target to build an object file
ba2D3DboxType.cc.o:
	$(MAKE) -f CMakeFiles/ba2D3DboxType1.dir/build.make CMakeFiles/ba2D3DboxType1.dir/ba2D3DboxType.cc.o
.PHONY : ba2D3DboxType.cc.o

ba2D3DboxType.i: ba2D3DboxType.cc.i
.PHONY : ba2D3DboxType.i

# target to preprocess a source file
ba2D3DboxType.cc.i:
	$(MAKE) -f CMakeFiles/ba2D3DboxType1.dir/build.make CMakeFiles/ba2D3DboxType1.dir/ba2D3DboxType.cc.i
.PHONY : ba2D3DboxType.cc.i

ba2D3DboxType.s: ba2D3DboxType.cc.s
.PHONY : ba2D3DboxType.s

# target to generate assembly for a file
ba2D3DboxType.cc.s:
	$(MAKE) -f CMakeFiles/ba2D3DboxType1.dir/build.make CMakeFiles/ba2D3DboxType1.dir/ba2D3DboxType.cc.s
.PHONY : ba2D3DboxType.cc.s

test.o: test.cc.o
.PHONY : test.o

# target to build an object file
test.cc.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cc.o
.PHONY : test.cc.o

test.i: test.cc.i
.PHONY : test.i

# target to preprocess a source file
test.cc.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cc.i
.PHONY : test.cc.i

test.s: test.cc.s
.PHONY : test.s

# target to generate assembly for a file
test.cc.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cc.s
.PHONY : test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ba2D3D"
	@echo "... ba2D3Dbox"
	@echo "... ba2D3DboxType1"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... ba2D3D.o"
	@echo "... ba2D3D.i"
	@echo "... ba2D3D.s"
	@echo "... ba2D3Dbox.o"
	@echo "... ba2D3Dbox.i"
	@echo "... ba2D3Dbox.s"
	@echo "... ba2D3DboxType.o"
	@echo "... ba2D3DboxType.i"
	@echo "... ba2D3DboxType.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

